import {
    SiApachekafka,
    SiApacheflink,
    SiRedhat,
    SiElasticsearch,
    SiMicrosoftsqlserver,
    SiProcessingfoundation,
    SiRedis,
    SiIbm,
    SiCloudways,
    SiGoogleplay,
    SiSpringboot,
    SiRedhatopenshift,
    SiDocker,
    SiApachehive,
    SiApachedruid,
    SiApacheairflow,
    SiApachecassandra,
    SiApachekylin,
    SiApachespark,
    SiJavascript,
    SiJava,
    SiPython,
    SiConfluence,
    SiMysql,
    SiMongodb,
    SiPostgresql,
    SiPowerbi,
    SiPrometheus,
    SiGraphql
} from 'react-icons/si';
import { FaWarehouse } from 'react-icons/fa';
import hbase from '../../asset/hbase.svg';
import kdb from '../../asset/kdb.svg';
import solace from '../../asset/solace.png';


export const ICONS = [<SiApacheflink className="logo" />,
<SiRedhat className="logo" />,
<SiProcessingfoundation className="logo" />,
<SiMicrosoftsqlserver className="logo" />,
<SiApachekafka className="logo" />,
<SiElasticsearch className="logo" />,
<img src={hbase} className="logo" alt="logo" />,
<img src={kdb} className="logo" alt="logo" />,
<SiRedis className="logo" />,
<SiIbm className="logo" />,
<SiCloudways className="logo" />,
<SiGoogleplay className="logo" />,
<FaWarehouse className="logo" />,
<img src={solace} className="logo" alt="logo" style={{ width: 40 }} />,

<SiGraphql className="logo" />,
<SiSpringboot className="logo" />,
<SiRedhatopenshift className="logo" />,
<SiDocker className="logo" />,
<SiApachehive className="logo" />,
<SiApachedruid className="logo" />,
<SiApacheairflow className="logo" />,
<SiApachecassandra className="logo" />,
<SiApachekylin className="logo" />,
<SiApachespark className="logo" />,
<SiJavascript className="logo" />,
<SiJava className="logo" />,
<SiPython className="logo" />,
<SiConfluence className="logo" />,
<SiMysql className="logo" />,
<SiMongodb className="logo" />,
<SiPostgresql className="logo" />,
<SiPowerbi className="logo" />,
<SiPrometheus className="logo" />,

];
